version: '2.0'

services:
  webapp:
    image: lvtest0.4
    ports:
    - "8000:4000"
    volumes:
    - .:/app
  redis:
    image: "redis:alpine"

# TODO IDEAS: Put nginx in front of it? Add postgres?

#########
# Usage #
#########

# docker-compose up -d

# docker-compose down

# docker logs --follow liveviewtest_webapp_1

# docker exec -it liveviewtest_webapp_1 bash
